### PR TITLE
add SetProcessDpiAwareness

### PR DESCRIPTION
**Pull request by ayasechan**

### CODE REVIEW

**Comment by gonutz** [comment]
Nice, thanks for the contribution. Can you make `SetProcessDpiAwareness` return either the `HRESULT` or an `error`?

**Comment by ayasechan** [comment]
I modified the pr
Is now okay?

**Comment by gonutz** [comment]
Very nice, thank you very much for you contribution, I really appreciate it!

**Comment by gonutz** [comment]
I just created a new tag for you - 2.2.5 - so you can update your go.mod file without any trouble.

**Pull request merged**
