### PR TITLE
Add GetWindowInfo

### PR DESCRIPTION
**Pull request by hulucc**

### CODE REVIEW

**Comment by gonutz** [comment]
Nice, thanks for contributing. One thing: can you change the signature to

    func GetWindowInfo(hwnd HWND) (WINDOWINFO, bool)

This way you do not have to declare a variable before using the function.

**Comment by hulucc** [comment]
I know that and I notice other function such as  `GetMonitorInfo` or `GetWindowPlacement` just form it as same as original win32 signature.
So should we keep consistency or just make it more go-style?

**Comment by gonutz** [comment]
You are correct, right now this is a mix of both styles. That was due to the fact that I originally forked this from Allen Dang and he had the Win API style everywhere.

But for Go I want it to fit in and be easy to use. Since we now have a mix, none of the options are consistent so I prefer the Go way. Do you agree?

It would actually be nice to have a v3 of this lib where everything gets cleaned up, but I have no time for that :-)

**Comment by hulucc** [comment]
Personally I think consistency is preferred over correctness, because the user have to suffer the incorrectness either way, at lease they can have the consistency.
But it's your call here. Fixed.

**Comment by gonutz** [comment]
Oh, you would prefer the non-Go way? Then, thanks for changing it anyway :-)

And thanks again for contributing, I really appreciate it.

**Comment by gonutz** [comment]
I made you a new tag, v2.5.0, for module support.

**Pull request merged**
