### PR TITLE
 # FIX - wrong messages

### PR DESCRIPTION
**Pull request by mang022**
- Fix wrong list box message constants

### CODE REVIEW

**Comment by gonutz** [comment]
Where did you get these constants from? Googling for it I find things like this header

https://github.com/rofl0r/microwindows/blob/master/src/include/winctl.h

where the constants start with `0xF`.

**Comment by mang022** [comment]
As I mentioned before, I got the constants from `wndhack`, http://aezay.dk/aezay/wndhack/ .

I found list box window in notepad++. I sent a message, LB_GETCOUNT start with `0xF`, but return value was 0, though there were lots of contents. I thought it's something wrong. So I found wndhack and sent the same message start with `0x0`. The return value was correct, the number of contents. Then, I fixed constants, it worked.

**Comment by gonutz** [comment]
You are right, those constants in the link I mentioned are wrong. Now I wonder if any of the others are wrong as well. I will check that soon and update the repository as needed. Maybe it is just the LB_ ones, then I can merge your PR, but maybe there are others in which case I will probably create my own commit. Thanks very much for finding this, great that you provide your help, I really appreciate it!

**Comment by gonutz** [comment]
Thank you again for your contribution, sorry it took me so long to get back to you. I have now checked all existing constants. It turns out there were a bunch more wrong. When I originally forked this repo from the original author I did not check these. Thank you very much for pointing out the issues. Since the changes of your PR are incorporated now, I will close this PR.

**Pull request closed without merging**
