### PR TITLE
 # FIX - windows messages

### PR DESCRIPTION
**Pull request by mang022**
- Fix windwos messages with reference to window hacker util made by aezay
- download at : http://aezay.dk/aezay/wndhack/

### CODE REVIEW

**Comment by mang022** [comment]
I'm creating some macros using your repository. Thank you for your work. I found wrong messages in list box constants. So I added, removed, and edited messages with reference to windows hacker util.

**Comment by gonutz** [comment]
Hey mang022, thank you very much for your contribution. Your commit is pretty large and most of it is just replacing numbers with themselves written in a slightly different way. While I appreciate the formatting of `0x1fa` to `0x1FA` which makes it more consistent, some things I like more the way they are, e.g. the `WM_USER + 1` instead of `0x0402` because it has documentary value.

Wrong message constants must be fixed of course, great that you caught them. But could you please split your PR into one commit that only fixes wrong constants, then another one that only formats `0x1fa` to `0x1FA`?

**Comment by gonutz** [comment]
I see that your PR contains additions, not only bug fixes. I will leave this open for now, when I get around to it I will add the EM_ and other constants. Thank you again for your work, I appreciate it very much.

**Comment by gonutz** [comment]
I have a few questions:

Where did you get the `LB_INSERTSTRINGUPPER` to `LB_SETITEMADDDATA` constants from? In the original fork they were called `LB_SETTEXT`... but when I try to print these from C++ they are all undefined. Now there are two different names for these constants, I wonder which ones are the ones to use.[](url)

Also there are constants like `WM_UNUSED0036`. Where is this USED? I think I will keep them anyway, that spy software seems to report it and it does not hurt.

I have already merged a lot of your PR into my latest changes (by hand, not using git merge or github's merge) and I am looking at the remaining constants to compare them to what C++ reports. So far all looks good.

**Pull request closed without merging**
