### PR TITLE
Add GetNumberOfEventLogRecords

### PR DESCRIPTION
**Pull request by wh1te909**

### CODE REVIEW

**Comment by gonutz** [comment]
Hey, thanks for the contribution.

I found the `MAX_RECORD_BUFFER_SIZE` constant in the sample at

https://docs.microsoft.com/en-us/windows/win32/eventlog/querying-for-event-source-messages

but where does the `MAX_BUFFER_SIZE` come from? I think neither of these should go into the `w32` library, they seem to be used locally in those examples. I could not find them in `windows.h` or `winbase.h` so just remove them.

Also I would adjust the function signature to be easier to use in Go by not passing in a pointer but rather return the value, like so:

    func GetNumberOfEventLogRecords(eventlog HANDLE) (numberofrecords uint32, ok bool) {
    	ret, _, _ := getNumberOfEventLogRecords.Call(
    		uintptr(eventlog),
    		uintptr(unsafe.Pointer(&numberofrecords)),
    	)
    	ok = ret != 0
    	return
    }

Could you make these changes, then I would merge your PR, looks good.

**Comment by gonutz** [comment]
While at it, just name the return value `n` instead of `numberofrecords` :-)

**Comment by wh1te909** [comment]
I found the constants here and just replicated xD https://github.com/JamesHovious/w32
Still new to golang and trying to learn the win32 api but you're right they don't belong here.
Adjusted the function thanks!

**Comment by gonutz** [comment]
Alright, again thank you very much, I really appreciate it!

**Pull request merged**
