### PR TITLE
Add File Stream API

### PR DESCRIPTION
**Pull request by lcostantino**
- FindFirstStreamW  (https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findfirststreamw)
    - FindNextStreamW   (https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findnextstreamw)
    - FindClose         (https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findclose)

### CODE REVIEW

**Comment by gonutz** [comment]
Hey, thanks for contributing!

I have some small issues, did you update `types.go` and `constants.go` but forgot to commit them? The following are undefined for me:
`WIN32_FIND_STREAM_DATA`
`ERROR_HANDLE_EOF`

Another thing that I would do is change the signature of `FindFirstStream`. Looking at the docs and at your code, it seems we can just say `FindFirstStream(filename string, data *WIN32_FIND_STREAM_DATA)` and always pass `FindStreamInfoStandard` for the info level and `0` for the flags parameter. These are currently all supported values anyway and if some time in the future it changes, we can adapt (I doubt that it will ever change).
This, however is just a suggestion and I am not really sure if it is right to change the API like this, although I have already adapted some of the Win32 API functions to Go like this. In this case I will leave it up to you what to do, this is your pull request after all ;-)

Still, please add the undefined type and constant and we are good to go. Thanks very much :-)

**Comment by lcostantino** [comment]
Thanks gonutz,

yes, i've missed those changes (Working locally in another machine!).
Also did the changes on the API since looks better right now.

Let me know if there's something else wrong or missing.
regards!

**Comment by gonutz** [comment]
Nice, thanks!

Upon checking your code I found that you declare
`const ERROR_HANDLE_EOF = ^HANDLE(38)`
where I found in the actual Win API header file that it should just be
`const ERROR_HANDLE_EOF = 38`

I guess you used the other code there as a reference, where it says
`const INVALID_HANDLE_VALUE = ^HANDLE(0)`
but that is just there to signify `-1` as a handle. The syntax is there because a HANDLE is an unsigned type so you cannot write `handle = -1` in Go, as negative values underflow unsigned types. That is why we negate `0` and that way get the handle value `-1` on both 32 bit and 64 bit Windows systems.

Please make your const just a `= 38`, without the `HANDLE` type, this way it can be used to compare agains other types of values without casting it.

The rest of the code looks good, have you tested it with a real example to make sure that it works as expected for you? You should have gotten into trouble with the constant thing before...

**Comment by lcostantino** [comment]
Actually i've removed the EOF since it's part of GetLastError and that's why it was working (because it matched the ivnalid handle value).
In case someone need to determine wheter there are no streams or it failed because another reason we can change it in the future.

Some test sample (you can ignore the syscall utf16 if needed, is just a sample)

func main() {

	bs := w32.WIN32_FIND_STREAM_DATA{}
	
	if hh, ok := w32.FindFirstStream(os.Args[1], &bs); ok {
		for ok {
			bs = w32.WIN32_FIND_STREAM_DATA{}
			if ok = w32.FindNextStream(hh, &bs); ok {
				streamName := syscall.UTF16ToString(bs.Name[:])
				fmt.Println("Stream is ", streamName)
			}
		}
		w32.FindClose(hh)
	}
}

**Comment by gonutz** [comment]
Alright, merged it. Again, thank you very much!

Ich just refactored it a little because I do not like the hungarian notation in those Windows API parameter names. I think it was a good idea of you to include the Boolean return value to FindFirstStream, often when a `HANDLE` is returned I check for `0`, but sometimes it is `INVALID_HANDLE_VALUE`. Having a `bool` along with the handle value makes a nice API I think.

**Pull request merged**
