### PR TITLE
Add WS_EX_COMPOSITED constant

### PR DESCRIPTION
**Pull request by ghost**
https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles

### CODE REVIEW

**Comment by gonutz** [comment]
Cool, thanks for the contribution. And nicely spotted formatting issue with the hex constant :-)

**Comment by gonutz** [comment]
Do you want me to tag a new version for you, I know go modules make life hard these days?

**Comment by n1ghtd3v** [comment]
Hello, thank you for getting back to me so quick, yes indeed, it would be great to just increment as a minor version.

I plan to update some other things later on, but it's going to be more than that.

**Comment by gonutz** [comment]
Cool, on it.

**Comment by gonutz** [comment]
OK, done. Thanks again for helping out. It is always nice to see more people participate, I really appreciate it!

**Comment by n1ghtd3v** [comment]
Thank you, seeing that you are active to maintain this repository encourages to contribute.

**Pull request merged**
